name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: permission
        run: chmod +x configure
      - name: configure
        run: ./configure
      - name: make
        run: make $(nproc)