name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: install doctest
        run: sudo apt-get install -y doctest-dev
      - name: permission
        run: chmod +x configure
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: test
        run: make test
      - name: clean
        run: make clean